import{a as v,S as q,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const R="https://pixabay.com/api/",A="52775931-16083de2a094930dd1fb1c03d",P={key:A,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function y(o,r=1){try{return(await v.get(R,{params:{...P,q:o,page:r}})).data}catch(e){throw e}}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),d=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const r=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${e.likes}</li>
          <li><b>Views:</b> ${e.views}</li>
          <li><b>Comments:</b> ${e.comments}</li>
          <li><b>Downloads:</b> ${e.downloads}</li>
        </ul>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),$.refresh()}function h(){m.innerHTML=""}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){d&&d.classList.remove("hidden")}function n(){d&&d.classList.add("hidden")}const B=document.querySelector(".form"),E=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more"),O=document.querySelector(".gallery");let l="",i=1,f=0;const S=15;B.addEventListener("submit",async o=>{o.preventDefault();const r=E.value.trim();if(!r){a.warning({message:"Please enter a search term!",position:"topRight"});return}r!==l?(l=r,i=1,h(),n()):(i=1,h(),n());try{b();const e=await y(l,i);if(!e||!Array.isArray(e.hits)||e.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n();return}f=e.totalHits,p(e.hits),i*S<f?w():(n(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.error(e),a.error({message:"An error occurred while fetching images.",position:"topRight"})}finally{L()}});M.addEventListener("click",async()=>{i+=1,n();try{b();const o=await y(l,i);if(!o||!Array.isArray(o.hits)||o.hits.length===0){a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n();return}p(o.hits);const r=O.querySelector(".gallery-item");if(r){const{height:c}=r.getBoundingClientRect();window.scrollBy({top:c*2,behavior:"smooth"})}i*S<f?w():(n(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error(o),a.error({message:"An error occurred while fetching images.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
